services:
  webrtc-app:
    build: .
    container_name: webrtc-cv
    command: python server.py -host "0.0.0.0" >> out/logs.txt 2>&1
    # I don't have gpu on the server
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    ports:
      - 5000:5000
    volumes:
      - ./out/:/app/out/
    restart: unless-stopped