services:
  webrtc-app:
    build: .
    container_name: webrtc-cv
    command: python server.py >> logs.txt 2>&1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "5000:5000"
    volumes:
      - ./logs.txt:/app/logs.txt
    restart: unless-stopped